export const PresenceActionTypes = {
  GET_PRESENT_USERS_SUCCESS: "GET_PRESENT_USERS_SUCCESS",
  GET_PRESENT_USERS_START: "GET_PRESENT_USERS_START",
  PRESENT_USERS_FAILURE: "PRESENT_USERS_FAILURE"
};
